### PR TITLE
valvenewsMega

### PR DESCRIPTION
**Pull request by sketchedgrey**
No idea what this is but I'll roll with it.

Just some extra valvenewsMegas because valvenewsMega, I guess? The pictures should show up once merged. If not I'll fix that.

### CODE REVIEW

**Comment by CE1CECL** [comment]
we usually only keep originals here

although maybe make a unofficial folder and with a new readme should work with @leapofazzam123

**Comment by sketchedgrey** [comment]
> we usually only keep originals here
> 
> 
> 
> although maybe make a unofficial folder and with a new readme should work with @leapofazzam123 

Alright, I shall update my PR with another commit.

**Comment by sketchedgrey** [comment]
Done!

**Review by CE1CECL — APPROVED** [review]

**Review by sketchedgrey — COMMENTED** [review]
Good?

**Comment by sketchedgrey** [comment]
Yeah can you merge this?

**Comment by CE1CECL** [comment]
unfortunately i cant do it myself since i dont have write access
what i did earlier was something else idek what i did

**Pull request merged**
